import streamlit as st
import tensorflow as tf
import joblib
import numpy as np

st.set_page_config(
    page_title="MediGuide AI",
    page_icon="🩺",
    layout="wide"
)

# ------------------------
# CSS
# ------------------------

st.markdown("""
<style>

.stApp{
background:#0d1117;
color:white;
}

textarea{
background:white !important;
color:black !important;
}

.stButton>button{
background:#16a34a;
color:white;
border-radius:10px;
height:3em;
font-size:18px;
}

</style>
""", unsafe_allow_html=True)

# ------------------------
# Load
# ------------------------

model = tf.keras.models.load_model("model.keras")

encoder = joblib.load("label_encoder.pkl")

# rebuild vectorizer vocabulary (needed by model serialization safety)
# only needed if using external vocab elsewhere

st.title("🩺 MediGuide AI")

st.write(
    "Educational symptom checker powered by TensorFlow."
)

text = st.text_area(
    "Describe your symptoms",
    placeholder="Example: fever, headache, sore throat..."
)

if st.button("Analyze"):

    if len(text.strip()) == 0:
        st.warning("Please enter symptoms.")
        st.stop()

    pred = model.predict(np.array([text]), verbose=0)[0]

    top = np.argsort(pred)[::-1][:3]

    st.subheader("Possible Conditions")

    for idx in top:

        disease = encoder.inverse_transform([idx])[0]

        confidence = pred[idx] * 100

        st.progress(float(pred[idx]))

        st.write(
            f"**{disease}** : {confidence:.2f}%"
        )

    st.info("""
These predictions are generated by a machine learning model for educational purposes only.

Please consult a licensed healthcare professional for diagnosis and treatment.
""")

st.divider()

st.subheader("General Health Advice")

st.write("""
• Stay hydrated.

• Get proper rest.

• Monitor symptoms.

• Seek immediate medical care for severe pain, breathing difficulty,
persistent high fever, or loss of consciousness.
""")
